name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@5dafb461cea1f8b296d89297dc6de7bd0891f0d2 # v0.44.2
    with:
      image: ghcr.io/radiorabe/nginx
      name: nginx
      display-name: RaBe nginx in UBI9
      tags: minimal rhel9 ubi9 rabe nginx
      cosign-image-skip-regexp: quay.io/sclorg/nginx-122-micro-c9s
  release-mkdocs:
    permissions:
      contents: write # Required to push the gh-pages branch for documentation deployment
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@5dafb461cea1f8b296d89297dc6de7bd0891f0d2 # v0.44.2
  github-actions:
    permissions:
      contents: read
      security-events: write # so zizmor can publish results to the Security tab
    uses: radiorabe/actions/.github/workflows/test-github-actions.yaml@5dafb461cea1f8b296d89297dc6de7bd0891f0d2 # v0.44.2
